server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://db.xxxxxx.supabase.co:5432/postgres
    username: postgres
    password: your-supabase-db-password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    property-naming-strategy: SNAKE_CASE
